# Use a imagem base do Node.js
FROM node:14

# Crie um diretório de trabalho no contêiner
WORKDIR /app

# Copie o restante dos arquivos do aplicativo
COPY . .

# Exponha a porta em que o aplicativo será executado
EXPOSE 3000

